name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploytestapp:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.26.2'

      - name: Deploy to Kubernetes
        run: |
          kubectl get pods
