name: Deploy to Kubernetes

on:
  pull_request:
#    branches:
#      - test

jobs:
  deploytestapp:
    runs-on: ["self-hosted"]
    container: bitnami/kubectl:latest
    steps:
      - name: check to Kubernetes
        run: |
          kubectl get pods
