name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploytestapp:
    runs-on: ["self-hosted"]
    container: bitnami/kubectl:latest
    steps:
      - name: check to Kubernetes
        run: |
          kubectl get pod
