apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.appname }}
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Values.metadata.appname }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.cport }}
              protocol: TCP